Repository wei2912/planwithus-lib, pull requests merged in 2021-07, with the labels that each got.

#58 Update documentation
  README.md
  src/block/blockId/index.ts
  src/block/blockId/types.ts
  src/block/index.ts
  src/directory/index.ts
  src/index.ts
  src/matchRule/index.ts
  src/matchRule/pattern/index.ts
  src/module/index.ts
  src/module/types.ts
  src/parser/index.ts
  src/satisfier/index.ts
  src/satisfier/types.ts
  src/satisfyRule/index.ts
  src/satisfyRule/inequality/index.ts
  src/some/index.ts
  src/some/types.ts
Labels: enhancement, help wanted

#68 directory: Add retrieveTopLevel
  src/directory/index.ts
Labels: enhancement

#67 Setup rollup for bundling for browser usage
  .github/workflows/test-and-docs.yml
  .gitignore
  blocks/index.browser.js
  blocks/index.ts
  package-lock.json
  package.json
  rollup.config.js
  src/directory/index.ts
  src/index.test.ts
  src/index.ts
  tsconfig.bundle.json
Labels: WIP

#69 Setup bundle upload step in workflow
  .github/workflows/test-and-docs.yml
Labels: WIP

#74 Replace concept of top level blocks with selectable blocks
  blocks/minor/ma-2019.yml
  blocks/primary/cs-hons-2020/cs-hons-2020.yml
  blocks/primary/dsa-hons-2017.yml
  blocks/primary/ma-hons-2019.yml
  blocks/second/ma-2019.yml
  src/block/index.test.ts
  src/block/index.ts
  src/block/schemas.test.ts
  src/block/schemas.ts
  src/block/types.ts
  src/directory/index.ts
Labels: enhancement
